-- 生成50个产品的SQL脚本
-- 产品数据包含：名称、翻译、描述、参数、价格、图片等

-- 产品1-15: 紫砂壶 (category_id=1)
INSERT INTO products (id, name, name_en, name_ar, description, price, original_price, stock, category_id, image, images, capacity, weight, material, height, width) VALUES
(1, '西施紫砂壶', 'Xishi Zisha Teapot', 'إبريق زيشا شي شي', '西施壶，壶身圆润如西施之乳，壶嘴短俏，壶把倒把，是紫砂壶中最经典的壶型之一。采用原矿紫泥制作，泥质细腻，色泽温润。', 1280, 1280, 25, 1, '/images/products/1_西施紫砂壶_1.jpg', '["/images/products/1_西施紫砂壶_1.jpg","/images/products/1_西施紫砂壶_2.jpg","/images/products/1_西施紫砂壶_3.jpg","/images/products/1_西施紫砂壶_4.jpg","/images/products/1_西施紫砂壶_5.jpg","/images/products/1_西施紫砂壶_6.jpg"]', '200ml', '220g', '原矿紫泥', '7.5cm', '12cm'),
(2, '掇球紫砂壶', 'Duoqiu Zisha Teapot', 'إبريق زيشا ديو تشيو', '掇球壶，壶身如大球，壶盖如小球，壶钮如小小球，三球相掇，层次分明。造型饱满圆润，线条流畅。', 1580, 1580, 18, 1, '/images/products/2_掇球紫砂壶_1.jpg', '["/images/products/2_掇球紫砂壶_1.jpg","/images/products/2_掇球紫砂壶_2.jpg","/images/products/2_掇球紫砂壶_3.jpg","/images/products/2_掇球紫砂壶_4.jpg","/images/products/2_掇球紫砂壶_5.jpg","/images/products/2_掇球紫砂壶_6.jpg"]', '250ml', '280g', '底槽清', '8.5cm', '13cm'),
(3, '石瓢紫砂壶', 'Shipiao Zisha Teapot', 'إبريق زيشا شي بياو', '石瓢壶，壶身呈梯形，壶嘴直流，壶把三角，壶底三足支撑。造型稳重，出水流畅，是实用与美观的完美结合。', 980, 980, 30, 1, '/images/products/3_石瓢紫砂壶_1.jpg', '["/images/products/3_石瓢紫砂壶_1.jpg","/images/products/3_石瓢紫砂壶_2.jpg","/images/products/3_石瓢紫砂壶_3.jpg","/images/products/3_石瓢紫砂壶_4.jpg","/images/products/3_石瓢紫砂壶_5.jpg","/images/products/3_石瓢紫砂壶_6.jpg"]', '180ml', '190g', '原矿清水泥', '6.8cm', '11cm'),
(4, '仿古紫砂壶', 'Fangu Zisha Teapot', 'إبريق زيشا فانغو', '仿古壶，壶身扁圆，壶嘴微翘，壶把圆润。造型古朴典雅，传承传统工艺，是品茗收藏的佳品。', 1180, 1180, 22, 1, '/images/products/4_仿古紫砂壶_1.jpg', '["/images/products/4_仿古紫砂壶_1.jpg","/images/products/4_仿古紫砂壶_2.jpg","/images/products/4_仿古紫砂壶_3.jpg","/images/products/4_仿古紫砂壶_4.jpg","/images/products/4_仿古紫砂壶_5.jpg","/images/products/4_仿古紫砂壶_6.jpg"]', '220ml', '240g', '原矿紫泥', '7.2cm', '12.5cm'),
(5, '秦权紫砂壶', 'Qinquan Zisha Teapot', 'إبريق زيشا تشين تشوان', '秦权壶，壶身如秤砣，壶嘴短直，壶把环形。造型稳重如权，寓意权衡公正，是商务送礼的佳选。', 1380, 1380, 20, 1, '/images/products/5_秦权紫砂壶_1.jpg', '["/images/products/5_秦权紫砂壶_1.jpg","/images/products/5_秦权紫砂壶_2.jpg","/images/products/5_秦权紫砂壶_3.jpg","/images/products/5_秦权紫砂壶_4.jpg","/images/products/5_秦权紫砂壶_5.jpg","/images/products/5_秦权紫砂壶_6.jpg"]', '190ml', '210g', '底槽清', '7.8cm', '11.5cm'),
(6, '井栏紫砂壶', 'Jinglan Zisha Teapot', 'إبريق زيشا جينغ لان', '井栏壶，壶身如井栏，壶盖如井盖，壶钮如井绳。造型源自古代井栏，寓意饮水思源，古朴典雅。', 1080, 1080, 28, 1, '/images/products/6_井栏紫砂壶_1.jpg', '["/images/products/6_井栏紫砂壶_1.jpg","/images/products/6_井栏紫砂壶_2.jpg","/images/products/6_井栏紫砂壶_3.jpg","/images/products/6_井栏紫砂壶_4.jpg","/images/products/6_井栏紫砂壶_5.jpg","/images/products/6_井栏紫砂壶_6.jpg"]', '210ml', '230g', '原矿段泥', '8cm', '12cm'),
(7, '水平紫砂壶', 'Shuiping Zisha Teapot', 'إبريق زيشا شوي بينغ', '水平壶，壶身圆润，壶嘴短俏，壶把圆润。造型小巧玲珑，适合功夫茶冲泡，是潮汕功夫茶的经典器具。', 880, 880, 35, 1, '/images/products/7_水平紫砂壶_1.jpg', '["/images/products/7_水平紫砂壶_1.jpg","/images/products/7_水平紫砂壶_2.jpg","/images/products/7_水平紫砂壶_3.jpg","/images/products/7_水平紫砂壶_4.jpg","/images/products/7_水平紫砂壶_5.jpg","/images/products/7_水平紫砂壶_6.jpg"]', '150ml', '160g', '原矿朱泥', '6cm', '10cm'),
(8, '潘壶紫砂壶', 'Panhu Zisha Teapot', 'إبريق زيشا بان هو', '潘壶，壶身扁圆，壶嘴微翘，壶把圆润。造型源自清代潘氏，是文人雅士喜爱的壶型，适合品茗论道。', 1680, 1680, 15, 1, '/images/products/8_潘壶紫砂壶_1.jpg', '["/images/products/8_潘壶紫砂壶_1.jpg","/images/products/8_潘壶紫砂壶_2.jpg","/images/products/8_潘壶紫砂壶_3.jpg","/images/products/8_潘壶紫砂壶_4.jpg","/images/products/8_潘壶紫砂壶_5.jpg","/images/products/8_潘壶紫砂壶_6.jpg"]', '230ml', '260g', '原矿紫泥', '7.5cm', '13cm'),
(9, '鱼化龙紫砂壶', 'Yuhualong Zisha Teapot', 'إبريق زيشا يو هوا لونغ', '鱼化龙壶，壶身饰以鱼鳞纹，壶钮为龙形，寓意鱼跃龙门。工艺精湛，是紫砂壶中的精品。', 1980, 1980, 12, 1, '/images/products/9_鱼化龙紫砂壶_1.jpg', '["/images/products/9_鱼化龙紫砂壶_1.jpg","/images/products/9_鱼化龙紫砂壶_2.jpg","/images/products/9_鱼化龙紫砂壶_3.jpg","/images/products/9_鱼化龙紫砂壶_4.jpg","/images/products/9_鱼化龙紫砂壶_5.jpg","/images/products/9_鱼化龙紫砂壶_6.jpg"]', '260ml', '290g', '底槽清', '8.5cm', '14cm'),
(10, '松竹梅紫砂壶', 'Songzhumei Zisha Teapot', 'إبريق زيشا سونغ تشو مي', '松竹梅壶，壶身饰以松竹梅三友图案，寓意岁寒三友，高洁品格。工艺精细，是收藏佳品。', 1880, 1880, 14, 1, '/images/products/10_松竹梅紫砂壶_1.jpg', '["/images/products/10_松竹梅紫砂壶_1.jpg","/images/products/10_松竹梅紫砂壶_2.jpg","/images/products/10_松竹梅紫砂壶_3.jpg","/images/products/10_松竹梅紫砂壶_4.jpg","/images/products/10_松竹梅紫砂壶_5.jpg","/images/products/10_松竹梅紫砂壶_6.jpg"]', '240ml', '270g', '原矿紫泥', '8cm', '13.5cm'),
(11, '菊瓣紫砂壶', 'Juban Zisha Teapot', 'إبريق زيشا تشو بان', '菊瓣壶，壶身如菊花瓣，层次分明，线条流畅。造型优美，如盛开的菊花，是花器中的经典。', 1480, 1480, 18, 1, '/images/products/11_菊瓣紫砂壶_1.jpg', '["/images/products/11_菊瓣紫砂壶_1.jpg","/images/products/11_菊瓣紫砂壶_2.jpg","/images/products/11_菊瓣紫砂壶_3.jpg","/images/products/11_菊瓣紫砂壶_4.jpg","/images/products/11_菊瓣紫砂壶_5.jpg","/images/products/11_菊瓣紫砂壶_6.jpg"]', '200ml', '230g', '原矿段泥', '7.8cm', '12.5cm'),
(12, '竹节紫砂壶', 'Zhujie Zisha Teapot', 'إبريق زيشا تشو جيه', '竹节壶，壶身如竹节，壶嘴壶把如竹枝，寓意节节高升。造型清新雅致，适合品茗养生。', 1380, 1380, 20, 1, '/images/products/12_竹节紫砂壶_1.jpg', '["/images/products/12_竹节紫砂壶_1.jpg","/images/products/12_竹节紫砂壶_2.jpg","/images/products/12_竹节紫砂壶_3.jpg","/images/products/12_竹节紫砂壶_4.jpg","/images/products/12_竹节紫砂壶_5.jpg","/images/products/12_竹节紫砂壶_6.jpg"]', '190ml', '220g', '原矿紫泥', '7.5cm', '12cm'),
(13, '海棠紫砂壶', 'Haitang Zisha Teapot', 'إبريق زيشا هاي تانغ', '海棠壶，壶身如海棠花，四瓣对称，造型优美。线条流畅，如海棠花开，是花器中的精品。', 1580, 1580, 16, 1, '/images/products/13_海棠紫砂壶_1.jpg', '["/images/products/13_海棠紫砂壶_1.jpg","/images/products/13_海棠紫砂壶_2.jpg","/images/products/13_海棠紫砂壶_3.jpg","/images/products/13_海棠紫砂壶_4.jpg","/images/products/13_海棠紫砂壶_5.jpg","/images/products/13_海棠紫砂壶_6.jpg"]', '210ml', '240g', '底槽清', '8cm', '12.8cm'),
(14, '瓜棱紫砂壶', 'Gualeng Zisha Teapot', 'إبريق زيشا كوا لينغ', '瓜棱壶，壶身如瓜棱，线条分明，造型饱满。如成熟的瓜果，寓意丰收吉祥，是实用与美观的结合。', 1280, 1280, 22, 1, '/images/products/14_瓜棱紫砂壶_1.jpg', '["/images/products/14_瓜棱紫砂壶_1.jpg","/images/products/14_瓜棱紫砂壶_2.jpg","/images/products/14_瓜棱紫砂壶_3.jpg","/images/products/14_瓜棱紫砂壶_4.jpg","/images/products/14_瓜棱紫砂壶_5.jpg","/images/products/14_瓜棱紫砂壶_6.jpg"]', '220ml', '250g', '原矿清水泥', '7.8cm', '13cm'),
(15, '扁壶紫砂壶', 'Bianhu Zisha Teapot', 'إبريق زيشا بين هو', '扁壶，壶身扁平，壶嘴短俏，壶把圆润。造型独特，适合冲泡绿茶，是绿茶爱好者的佳选。', 980, 980, 30, 1, '/images/products/15_扁壶紫砂壶_1.jpg', '["/images/products/15_扁壶紫砂壶_1.jpg","/images/products/15_扁壶紫砂壶_2.jpg","/images/products/15_扁壶紫砂壶_3.jpg","/images/products/15_扁壶紫砂壶_4.jpg","/images/products/15_扁壶紫砂壶_5.jpg","/images/products/15_扁壶紫砂壶_6.jpg"]', '180ml', '200g', '原矿紫泥', '6.5cm', '11.5cm');

-- 产品16-24: 紫砂茶杯 (category_id=2)
INSERT INTO products (id, name, name_en, name_ar, description, price, original_price, stock, category_id, image, images, capacity, weight, material, height, width) VALUES
(16, '圆口紫砂茶杯', 'Round Rim Zisha Teacup', 'فنجان زيشا دائري الفم', '圆口茶杯，杯口圆润，杯身饱满，手感舒适。采用原矿紫泥制作，适合品茗各类茶叶。', 128, 128, 80, 2, '/images/products/16_圆口紫砂茶杯_1.jpg', '["/images/products/16_圆口紫砂茶杯_1.jpg","/images/products/16_圆口紫砂茶杯_2.jpg","/images/products/16_圆口紫砂茶杯_3.jpg","/images/products/16_圆口紫砂茶杯_4.jpg","/images/products/16_圆口紫砂茶杯_5.jpg","/images/products/16_圆口紫砂茶杯_6.jpg"]', '80ml', '65g', '原矿紫泥', '4.5cm', '6.5cm'),
(17, '撇口紫砂茶杯', 'Flared Rim Zisha Teacup', 'فنجان زيشا مفتوح الفم', '撇口茶杯，杯口外撇，利于散热，适合品饮热茶。造型优雅，是功夫茶的经典器具。', 158, 158, 65, 2, '/images/products/17_撇口紫砂茶杯_1.jpg', '["/images/products/17_撇口紫砂茶杯_1.jpg","/images/products/17_撇口紫砂茶杯_2.jpg","/images/products/17_撇口紫砂茶杯_3.jpg","/images/products/17_撇口紫砂茶杯_4.jpg","/images/products/17_撇口紫砂茶杯_5.jpg","/images/products/17_撇口紫砂茶杯_6.jpg"]', '90ml', '70g', '底槽清', '5cm', '6.8cm'),
(18, '直口紫砂茶杯', 'Straight Rim Zisha Teacup', 'فنجان زيشا مستقيم الفم', '直口茶杯，杯口直立，杯身挺拔，造型简洁大方。适合品茗普洱、乌龙等茶类。', 138, 138, 75, 2, '/images/products/18_直口紫砂茶杯_1.jpg', '["/images/products/18_直口紫砂茶杯_1.jpg","/images/products/18_直口紫砂茶杯_2.jpg","/images/products/18_直口紫砂茶杯_3.jpg","/images/products/18_直口紫砂茶杯_4.jpg","/images/products/18_直口紫砂茶杯_5.jpg","/images/products/18_直口紫砂茶杯_6.jpg"]', '85ml', '68g', '原矿清水泥', '4.8cm', '6.2cm'),
(19, '花口紫砂茶杯', 'Flower Rim Zisha Teacup', 'فنجان زيشا مزخرف الفم', '花口茶杯，杯口如花边，造型优美，如盛开的花朵。适合女士品茗，增添优雅气质。', 188, 188, 50, 2, '/images/products/19_花口紫砂茶杯_1.jpg', '["/images/products/19_花口紫砂茶杯_1.jpg","/images/products/19_花口紫砂茶杯_2.jpg","/images/products/19_花口紫砂茶杯_3.jpg","/images/products/19_花口紫砂茶杯_4.jpg","/images/products/19_花口紫砂茶杯_5.jpg","/images/products/19_花口紫砂茶杯_6.jpg"]', '75ml', '62g', '原矿段泥', '4.2cm', '6.8cm'),
(20, '八方紫砂茶杯', 'Octagonal Zisha Teacup', 'فنجان زيشا ثماني الأضلاع', '八方茶杯，杯身八棱，造型独特，寓意八方来财。工艺复杂，是收藏把玩的佳品。', 218, 218, 45, 2, '/images/products/20_八方紫砂茶杯_1.jpg', '["/images/products/20_八方紫砂茶杯_1.jpg","/images/products/20_八方紫砂茶杯_2.jpg","/images/products/20_八方紫砂茶杯_3.jpg","/images/products/20_八方紫砂茶杯_4.jpg","/images/products/20_八方紫砂茶杯_5.jpg","/images/products/20_八方紫砂茶杯_6.jpg"]', '95ml', '75g', '原矿紫泥', '5.2cm', '7cm'),
(21, '斗笠紫砂茶杯', 'Douli Zisha Teacup', 'فنجان زيشا دو لي', '斗笠杯，杯形如斗笠，口大底小，利于观赏茶汤。是品茗绿茶、白茶的佳器。', 168, 168, 60, 2, '/images/products/21_斗笠紫砂茶杯_1.jpg', '["/images/products/21_斗笠紫砂茶杯_1.jpg","/images/products/21_斗笠紫砂茶杯_2.jpg","/images/products/21_斗笠紫砂茶杯_3.jpg","/images/products/21_斗笠紫砂茶杯_4.jpg","/images/products/21_斗笠紫砂茶杯_5.jpg","/images/products/21_斗笠紫砂茶杯_6.jpg"]', '100ml', '72g', '底槽清', '5.5cm', '7.2cm'),
(22, '铃铛紫砂茶杯', 'Bell Zisha Teacup', 'فنجان زيشا على شكل جرس', '铃铛杯，杯形如铃铛，杯身高挑，线条优美。适合品茗乌龙茶，聚香效果好。', 148, 148, 70, 2, '/images/products/22_铃铛紫砂茶杯_1.jpg', '["/images/products/22_铃铛紫砂茶杯_1.jpg","/images/products/22_铃铛紫砂茶杯_2.jpg","/images/products/22_铃铛紫砂茶杯_3.jpg","/images/products/22_铃铛紫砂茶杯_4.jpg","/images/products/22_铃铛紫砂茶杯_5.jpg","/images/products/22_铃铛紫砂茶杯_6.jpg"]', '110ml', '78g', '原矿紫泥', '6cm', '6.5cm'),
(23, '鸡心紫砂茶杯', 'Chicken Heart Zisha Teacup', 'فنجان زيشا على شكل قلب الدجاجة', '鸡心杯，杯底如鸡心，杯身饱满，握感舒适。是传统经典杯型，适合日常品茗。', 118, 118, 85, 2, '/images/products/23_鸡心紫砂茶杯_1.jpg', '["/images/products/23_鸡心紫砂茶杯_1.jpg","/images/products/23_鸡心紫砂茶杯_2.jpg","/images/products/23_鸡心紫砂茶杯_3.jpg","/images/products/23_鸡心紫砂茶杯_4.jpg","/images/products/23_鸡心紫砂茶杯_5.jpg","/images/products/23_鸡心紫砂茶杯_6.jpg"]', '70ml', '58g', '原矿清水泥', '4cm', '6cm'),
(24, '圆底紫砂茶杯', 'Round Bottom Zisha Teacup', 'فنجان زيشا قاعدة دائرية', '圆底茶杯，杯底圆润，杯身稳重，放置平稳。适合品茗各类茶叶，是实用之选。', 98, 98, 95, 2, '/images/products/24_圆底紫砂茶杯_1.jpg', '["/images/products/24_圆底紫砂茶杯_1.jpg","/images/products/24_圆底紫砂茶杯_2.jpg","/images/products/24_圆底紫砂茶杯_3.jpg","/images/products/24_圆底紫砂茶杯_4.jpg","/images/products/24_圆底紫砂茶杯_5.jpg","/images/products/24_圆底紫砂茶杯_6.jpg"]', '65ml', '55g', '原矿紫泥', '3.8cm', '5.8cm');

-- 产品25-36: 茶叶罐 (category_id=3)
INSERT INTO products (id, name, name_en, name_ar, description, price, original_price, stock, category_id, image, images, capacity, weight, material, height, width) VALUES
(25, '汉铎紫砂壶', 'Handuo Zisha Teapot', 'إبريق زيشا هان دو', '汉铎壶，壶身如古代乐器铎，造型古朴，寓意警醒。是文人雅士喜爱的壶型。', 1680, 1680, 15, 1, '/images/products/25_汉铎紫砂壶_1.jpg', '["/images/products/25_汉铎紫砂壶_1.jpg","/images/products/25_汉铎紫砂壶_2.jpg","/images/products/25_汉铎紫砂壶_3.jpg","/images/products/25_汉铎紫砂壶_4.jpg","/images/products/25_汉铎紫砂壶_5.jpg","/images/products/25_汉铎紫砂壶_6.jpg"]', '200ml', '230g', '原矿紫泥', '7.5cm', '12cm'),
(26, '容天紫砂壶', 'Rongtian Zisha Teapot', 'إبريق زيشا رونغ تيان', '容天壶，壶身圆润如天，壶盖如天穹，寓意包容天下。造型大气，适合待客。', 1780, 1780, 14, 1, '/images/products/26_容天紫砂壶_1.jpg', '["/images/products/26_容天紫砂壶_1.jpg","/images/products/26_容天紫砂壶_2.jpg","/images/products/26_容天紫砂壶_3.jpg","/images/products/26_容天紫砂壶_4.jpg","/images/products/26_容天紫砂壶_5.jpg","/images/products/26_容天紫砂壶_6.jpg"]', '240ml', '270g', '底槽清', '8.2cm', '13cm');

-- 注意：产品25-26实际上是紫砂壶，继续添加茶叶罐
-- 重新检查分类，25-30应该是紫砂壶，31-36是茶叶罐
-- 让我修正并继续

-- 产品27-30: 紫砂壶 (category_id=1)
INSERT INTO products (id, name, name_en, name_ar, description, price, original_price, stock, category_id, image, images, capacity, weight, material, height, width) VALUES
(27, '子冶石瓢紫砂壶', 'Ziye Shipiao Zisha Teapot', 'إبريق زيشا شي بياو زي يه', '子冶石瓢，由清代瞿子冶创制，壶身刻绘竹枝，文人气息浓厚。是文人壶的代表。', 1880, 1880, 12, 1, '/images/products/27_子冶石瓢紫砂壶_1.jpg', '["/images/products/27_子冶石瓢紫砂壶_1.jpg","/images/products/27_子冶石瓢紫砂壶_2.jpg","/images/products/27_子冶石瓢紫砂壶_3.jpg","/images/products/27_子冶石瓢紫砂壶_4.jpg","/images/products/27_子冶石瓢紫砂壶_5.jpg","/images/products/27_子冶石瓢紫砂壶_6.jpg"]', '220ml', '250g', '原矿紫泥', '7.8cm', '12.5cm'),
(28, '景舟石瓢紫砂壶', 'Jingzhou Shipiao Zisha Teapot', 'إبريق زيشا شي بياو جينغ تشو', '景舟石瓢，由顾景舟大师改良，线条更加流畅优美。是石瓢壶中的精品，收藏价值高。', 2180, 2180, 10, 1, '/images/products/28_景舟石瓢紫砂壶_1.jpg', '["/images/products/28_景舟石瓢紫砂壶_1.jpg","/images/products/28_景舟石瓢紫砂壶_2.jpg","/images/products/28_景舟石瓢紫砂壶_3.jpg","/images/products/28_景舟石瓢紫砂壶_4.jpg","/images/products/28_景舟石瓢紫砂壶_5.jpg","/images/products/28_景舟石瓢紫砂壶_6.jpg"]', '230ml', '260g', '底槽清', '8cm', '13cm'),
(29, '匏尊紫砂壶', 'Baozun Zisha Teapot', 'إبريق زيشا باو زون', '匏尊壶，壶身如葫芦，寓意福禄双全。造型独特，工艺复杂，是收藏佳品。', 1580, 1580, 16, 1, '/images/products/29_匏尊紫砂壶_1.jpg', '["/images/products/29_匏尊紫砂壶_1.jpg","/images/products/29_匏尊紫砂壶_2.jpg","/images/products/29_匏尊紫砂壶_3.jpg","/images/products/29_匏尊紫砂壶_4.jpg","/images/products/29_匏尊紫砂壶_5.jpg","/images/products/29_匏尊紫砂壶_6.jpg"]', '210ml', '240g', '原矿段泥', '7.5cm', '12.8cm'),
(30, '思亭紫砂壶', 'Siting Zisha Teapot', 'إبريق زيشا سي تينغ', '思亭壶，由清代陆思亭创制，壶身如梨形，线条流畅。是清代经典壶型，古朴典雅。', 1480, 1480, 18, 1, '/images/products/30_思亭紫砂壶_1.jpg', '["/images/products/30_思亭紫砂壶_1.jpg","/images/products/30_思亭紫砂壶_2.jpg","/images/products/30_思亭紫砂壶_3.jpg","/images/products/30_思亭紫砂壶_4.jpg","/images/products/30_思亭紫砂壶_5.jpg","/images/products/30_思亭紫砂壶_6.jpg"]', '190ml', '220g', '原矿紫泥', '7.2cm', '11.8cm');

-- 产品31-36: 茶叶罐 (category_id=3)
INSERT INTO products (id, name, name_en, name_ar, description, price, original_price, stock, category_id, image, images, capacity, weight, material, height, width) VALUES
(31, '圆筒紫砂茶叶罐', 'Cylindrical Zisha Tea Caddy', 'علبة شاي زيشا أسطوانية', '圆筒茶叶罐，罐身圆筒形，密封性好，适合储存各类茶叶。造型简洁实用。', 380, 380, 45, 3, '/images/products/31_圆筒紫砂茶叶罐_1.jpg', '["/images/products/31_圆筒紫砂茶叶罐_1.jpg","/images/products/31_圆筒紫砂茶叶罐_2.jpg","/images/products/31_圆筒紫砂茶叶罐_3.jpg","/images/products/31_圆筒紫砂茶叶罐_4.jpg","/images/products/31_圆筒紫砂茶叶罐_5.jpg","/images/products/31_圆筒紫砂茶叶罐_6.jpg"]', '300g', '320g', '原矿紫泥', '12cm', '10cm'),
(32, '方形紫砂茶叶罐', 'Square Zisha Tea Caddy', 'علبة شاي زيشا مربعة', '方形茶叶罐，罐身四方形，造型稳重，寓意方正。适合储存普洱茶、黑茶等。', 420, 420, 40, 3, '/images/products/32_方形紫砂茶叶罐_1.jpg', '["/images/products/32_方形紫砂茶叶罐_1.jpg","/images/products/32_方形紫砂茶叶罐_2.jpg","/images/products/32_方形紫砂茶叶罐_3.jpg","/images/products/32_方形紫砂茶叶罐_4.jpg","/images/products/32_方形紫砂茶叶罐_5.jpg","/images/products/32_方形紫砂茶叶罐_6.jpg"]', '350g', '380g', '底槽清', '10cm', '10cm'),
(33, '竹节紫砂茶叶罐', 'Bamboo Joint Zisha Tea Caddy', 'علبة شاي زيشا على شكل عقدة الخيزران', '竹节茶叶罐，罐身如竹节，寓意节节高升。造型清新，适合储存绿茶、白茶等。', 450, 450, 35, 3, '/images/products/33_竹节紫砂茶叶罐_1.jpg', '["/images/products/33_竹节紫砂茶叶罐_1.jpg","/images/products/33_竹节紫砂茶叶罐_2.jpg","/images/products/33_竹节紫砂茶叶罐_3.jpg","/images/products/33_竹节紫砂茶叶罐_4.jpg","/images/products/33_竹节紫砂茶叶罐_5.jpg","/images/products/33_竹节紫砂茶叶罐_6.jpg"]', '280g', '300g', '原矿段泥', '11cm', '9cm'),
(34, '南瓜紫砂茶叶罐', 'Pumpkin Zisha Tea Caddy', 'علبة شاي زيشا على شكل يقطينة', '南瓜茶叶罐，罐身如南瓜，造型可爱，寓意丰收。适合储存乌龙茶、红茶等。', 480, 480, 30, 3, '/images/products/34_南瓜紫砂茶叶罐_1.jpg', '["/images/products/34_南瓜紫砂茶叶罐_1.jpg","/images/products/34_南瓜紫砂茶叶罐_2.jpg","/images/products/34_南瓜紫砂茶叶罐_3.jpg","/images/products/34_南瓜紫砂茶叶罐_4.jpg","/images/products/34_南瓜紫砂茶叶罐_5.jpg","/images/products/34_南瓜紫砂茶叶罐_6.jpg"]', '400g', '420g', '原矿紫泥', '12cm', '11cm'),
(35, '葫芦紫砂茶叶罐', 'Gourd Zisha Tea Caddy', 'علبة شاي زيشا على شكل قرع', '葫芦茶叶罐，罐身如葫芦，寓意福禄双全。造型优美，适合储存各类茶叶。', 520, 520, 28, 3, '/images/products/35_葫芦紫砂茶叶罐_1.jpg', '["/images/products/35_葫芦紫砂茶叶罐_1.jpg","/images/products/35_葫芦紫砂茶叶罐_2.jpg","/images/products/35_葫芦紫砂茶叶罐_3.jpg","/images/products/35_葫芦紫砂茶叶罐_4.jpg","/images/products/35_葫芦紫砂茶叶罐_5.jpg","/images/products/35_葫芦紫砂茶叶罐_6.jpg"]', '320g', '350g', '底槽清', '13cm', '9cm'),
(36, '鼓形紫砂茶叶罐', 'Drum Shape Zisha Tea Caddy', 'علبة شاي زيشا على شكل طبل', '鼓形茶叶罐，罐身如鼓，造型稳重，寓意鼓舞人心。密封性好，适合长期储存。', 550, 550, 25, 3, '/images/products/36_鼓形紫砂茶叶罐_1.jpg', '["/images/products/36_鼓形紫砂茶叶罐_1.jpg","/images/products/36_鼓形紫砂茶叶罐_2.jpg","/images/products/36_鼓形紫砂茶叶罐_3.jpg","/images/products/36_鼓形紫砂茶叶罐_4.jpg","/images/products/36_鼓形紫砂茶叶罐_5.jpg","/images/products/36_鼓形紫砂茶叶罐_6.jpg"]', '450g', '480g', '原矿紫泥', '11cm', '12cm');

-- 产品37-41: 茶具套装 (category_id=4)
INSERT INTO products (id, name, name_en, name_ar, description, price, original_price, stock, category_id, image, images, capacity, weight, material, height, width) VALUES
(37, '一壶两杯套装', 'One Pot Two Cups Tea Set', 'طقم شاي إبريق وفنجانين', '一壶两杯套装，包含一把紫砂壶和两个茶杯，适合二人品茗。配置齐全，送礼自用皆宜。', 1280, 1280, 20, 4, '/images/products/37_一壶两杯套装_1.jpg', '["/images/products/37_一壶两杯套装_1.jpg","/images/products/37_一壶两杯套装_2.jpg","/images/products/37_一壶两杯套装_3.jpg","/images/products/37_一壶两杯套装_4.jpg","/images/products/37_一壶两杯套装_5.jpg","/images/products/37_一壶两杯套装_6.jpg"]', '壶200ml/杯80ml', '650g', '原矿紫泥', '壶7cm/杯4cm', '壶12cm/杯6cm'),
(38, '一壶四杯套装', 'One Pot Four Cups Tea Set', 'طقم شاي إبريق وأربعة فناجين', '一壶四杯套装，包含一把紫砂壶和四个茶杯，适合小聚品茗。配置实用，家庭必备。', 1680, 1680, 15, 4, '/images/products/38_一壶四杯套装_1.jpg', '["/images/products/38_一壶四杯套装_1.jpg","/images/products/38_一壶四杯套装_2.jpg","/images/products/38_一壶四杯套装_3.jpg","/images/products/38_一壶四杯套装_4.jpg","/images/products/38_一壶四杯套装_5.jpg","/images/products/38_一壶四杯套装_6.jpg"]', '壶220ml/杯75ml', '850g', '底槽清', '壶7.5cm/杯4.2cm', '壶12.5cm/杯6.5cm'),
(39, '旅行茶具套装', 'Travel Tea Set', 'طقم شاي للسفر', '旅行茶具套装，包含便携茶壶、茶杯和收纳包，适合户外旅行使用。轻便实用，茶友必备。', 980, 980, 25, 4, '/images/products/39_旅行茶具套装_1.jpg', '["/images/products/39_旅行茶具套装_1.jpg","/images/products/39_旅行茶具套装_2.jpg","/images/products/39_旅行茶具套装_3.jpg","/images/products/39_旅行茶具套装_4.jpg","/images/products/39_旅行茶具套装_5.jpg","/images/products/39_旅行茶具套装_6.jpg"]', '壶180ml/杯60ml', '450g', '原矿紫泥', '壶6.5cm/杯3.5cm', '壶10cm/杯5cm'),
(40, '功夫茶具套装', 'Kung Fu Tea Set', 'طقم شاي الكونغ فو', '功夫茶具套装，包含茶壶、公道杯、品茗杯等全套器具，适合功夫茶冲泡。配置专业，茶艺必备。', 2180, 2180, 12, 4, '/images/products/40_功夫茶具套装_1.jpg', '["/images/products/40_功夫茶具套装_1.jpg","/images/products/40_功夫茶具套装_2.jpg","/images/products/40_功夫茶具套装_3.jpg","/images/products/40_功夫茶具套装_4.jpg","/images/products/40_功夫茶具套装_5.jpg","/images/products/40_功夫茶具套装_6.jpg"]', '壶200ml/杯50ml', '1200g', '原矿紫泥', '壶7cm/杯3.8cm', '壶12cm/杯5.5cm'),
(41, '茶盘茶具套装', 'Tea Tray Set', 'طقم شاي مع صينية', '茶盘茶具套装，包含茶盘、茶壶、茶杯等全套器具，配置齐全。适合家庭茶室使用，大气实用。', 2680, 2680, 10, 4, '/images/products/41_茶盘茶具套装_1.jpg', '["/images/products/41_茶盘茶具套装_1.jpg","/images/products/41_茶盘茶具套装_2.jpg","/images/products/41_茶盘茶具套装_3.jpg","/images/products/41_茶盘茶具套装_4.jpg","/images/products/41_茶盘茶具套装_5.jpg","/images/products/41_茶盘茶具套装_6.jpg"]', '壶220ml/杯70ml', '2800g', '底槽清', '壶7.5cm/杯4cm', '壶12.5cm/杯6cm');

-- 产品42-50: 配件 (category_id=5)
INSERT INTO products (id, name, name_en, name_ar, description, price, original_price, stock, category_id, image, images, capacity, weight, material, height, width) VALUES
(42, '紫砂茶漏', 'Zisha Tea Strainer', 'مصفاة شاي زيشا', '紫砂茶漏，用于过滤茶汤，防止茶叶进入杯中。做工精细，过滤效果好，是泡茶必备配件。', 68, 68, 120, 5, '/images/products/42_紫砂茶漏_1.jpg', '["/images/products/42_紫砂茶漏_1.jpg","/images/products/42_紫砂茶漏_2.jpg","/images/products/42_紫砂茶漏_3.jpg","/images/products/42_紫砂茶漏_4.jpg","/images/products/42_紫砂茶漏_5.jpg","/images/products/42_紫砂茶漏_6.jpg"]', 'N/A', '45g', '原矿紫泥', '5cm', '6cm'),
(43, '紫砂茶宠-貔貅', 'Zisha Tea Pet - Pixiu', 'تمثال شاي زيشا - بي شيو', '紫砂茶宠貔貅，传统招财神兽，寓意招财进宝。可养茶宠，随着茶汤滋养，色泽会越来越温润。', 128, 128, 80, 5, '/images/products/43_紫砂茶宠-貔貅_1.jpg', '["/images/products/43_紫砂茶宠-貔貅_1.jpg","/images/products/43_紫砂茶宠-貔貅_2.jpg","/images/products/43_紫砂茶宠-貔貅_3.jpg","/images/products/43_紫砂茶宠-貔貅_4.jpg","/images/products/43_紫砂茶宠-貔貅_5.jpg","/images/products/43_紫砂茶宠-貔貅_6.jpg"]', 'N/A', '85g', '原矿紫泥', '6cm', '8cm'),
(44, '紫砂茶夹', 'Zisha Tea Tongs', 'ملقط شاي زيشا', '紫砂茶夹，用于夹取茶杯，防止烫手。采用紫砂制作，手感温润，是功夫茶必备配件。', 58, 58, 150, 5, '/images/products/44_紫砂茶夹_1.jpg', '["/images/products/44_紫砂茶夹_1.jpg","/images/products/44_紫砂茶夹_2.jpg","/images/products/44_紫砂茶夹_3.jpg","/images/products/44_紫砂茶夹_4.jpg","/images/products/44_紫砂茶夹_5.jpg","/images/products/44_紫砂茶夹_6.jpg"]', 'N/A', '35g', '原矿紫泥', '18cm', '2cm'),
(45, '紫砂茶匙', 'Zisha Tea Spoon', 'ملعقة شاي زيشا', '紫砂茶匙，用于取茶叶，控制茶量。做工精细，是茶道六君子之一，泡茶必备。', 48, 48, 180, 5, '/images/products/45_紫砂茶匙_1.jpg', '["/images/products/45_紫砂茶匙_1.jpg","/images/products/45_紫砂茶匙_2.jpg","/images/products/45_紫砂茶匙_3.jpg","/images/products/45_紫砂茶匙_4.jpg","/images/products/45_紫砂茶匙_5.jpg","/images/products/45_紫砂茶匙_6.jpg"]', 'N/A', '25g', '原矿紫泥', '15cm', '2.5cm'),
(46, '紫砂茶漏托架', 'Zisha Tea Strainer Stand', 'حامل مصفاة شاي زيشا', '紫砂茶漏托架，用于放置茶漏，防止茶水滴落桌面。实用美观，是茶席上的好帮手。', 78, 78, 100, 5, '/images/products/46_紫砂茶漏托架_1.jpg', '["/images/products/46_紫砂茶漏托架_1.jpg","/images/products/46_紫砂茶漏托架_2.jpg","/images/products/46_紫砂茶漏托架_3.jpg","/images/products/46_紫砂茶漏托架_4.jpg","/images/products/46_紫砂茶漏托架_5.jpg","/images/products/46_紫砂茶漏托架_6.jpg"]', 'N/A', '65g', '原矿紫泥', '4cm', '7cm'),
(47, '紫砂茶垫', 'Zisha Tea Coaster', 'قاعدة فنجان شاي زيشا', '紫砂茶垫，用于放置茶杯，防止烫伤桌面。造型精美，是茶席上的点睛之笔。', 38, 38, 200, 5, '/images/products/47_紫砂茶垫_1.jpg', '["/images/products/47_紫砂茶垫_1.jpg","/images/products/47_紫砂茶垫_2.jpg","/images/products/47_紫砂茶垫_3.jpg","/images/products/47_紫砂茶垫_4.jpg","/images/products/47_紫砂茶垫_5.jpg","/images/products/47_紫砂茶垫_6.jpg"]', 'N/A', '40g', '原矿紫泥', '1.5cm', '8cm'),
(48, '紫砂茶则', 'Zisha Tea Scoop', 'مغرفة شاي زيشا', '紫砂茶则，用于量取茶叶，控制投茶量。是茶道六君子之一，体现茶人的专业素养。', 55, 55, 160, 5, '/images/products/48_紫砂茶则_1.jpg', '["/images/products/48_紫砂茶则_1.jpg","/images/products/48_紫砂茶则_2.jpg","/images/products/48_紫砂茶则_3.jpg","/images/products/48_紫砂茶则_4.jpg","/images/products/48_紫砂茶则_5.jpg","/images/products/48_紫砂茶则_6.jpg"]', 'N/A', '30g', '原矿紫泥', '12cm', '4cm'),
(49, '紫砂茶针', 'Zisha Tea Needle', 'إبرة شاي زيشا', '紫砂茶针，用于疏通壶嘴，清理茶渣。是茶道六君子之一，维护茶具的必备工具。', 42, 42, 190, 5, '/images/products/49_紫砂茶针_1.jpg', '["/images/products/49_紫砂茶针_1.jpg","/images/products/49_紫砂茶针_2.jpg","/images/products/49_紫砂茶针_3.jpg","/images/products/49_紫砂茶针_4.jpg","/images/products/49_紫砂茶针_5.jpg","/images/products/49_紫砂茶针_6.jpg"]', 'N/A', '20g', '原矿紫泥', '16cm', '0.8cm'),
(50, '紫砂茶拨', 'Zisha Tea Pick', 'مغرفة شاي زيشا', '紫砂茶拨，用于拨取茶叶，清理茶渣。是茶道六君子之一，泡茶必备配件。', 45, 45, 170, 5, '/images/products/50_紫砂茶拨_1.jpg', '["/images/products/50_紫砂茶拨_1.jpg","/images/products/50_紫砂茶拨_2.jpg","/images/products/50_紫砂茶拨_3.jpg","/images/products/50_紫砂茶拨_4.jpg","/images/products/50_紫砂茶拨_5.jpg","/images/products/50_紫砂茶拨_6.jpg"]', 'N/A', '22g', '原矿紫泥', '14cm', '1.2cm');
